VERSION_YEAR = 2024
VERSION_MONTH = int('01')
VERSION_DAY = int('31')
VERSION_HOUR = int('18')
VERSION_MINUTE = int('06')
MAJOR_VERSION = 1
MINOR_VERSION = 0
PATCH_VERSION = 202401311806
version_date = '2024/01/31 18:06'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
